stages:
  - build
  - deploy

variables:
  LOGGER_VERSION: 2021.2.0
  DOCKER_REGISTRY: NOT_SET
  REGION: $AWS_DEFAULT_REGION

  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

build:logger:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  tags:
    - aws
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "release"'
      when: on_success
  script: 
    - dotnet publish --configuration Release --output ./publish/
  artifacts:
    paths:
       - ./publish/*
    expire_in: 1 hour

deploy:logger:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [ "" ]
  needs: ["build:logger"]
  tags:
    - aws
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
      variables:
        DEPLOYMENT_ROLE: $AWS_STAGING_CI_ROLE_ARN
        DOCKER_REGISTRY: $AWS_STAGING_GAME_DOCKER_REPOSITORY
    - if: '$CI_COMMIT_BRANCH == "release"'
      when: on_success
      variables:
        DEPLOYMENT_ROLE: $AWS_PROD_CI_ROLE_ARN
        DOCKER_REGISTRY: $AWS_PROD_GAME_DOCKER_REPOSITORY
  variables:
    APP_NAME: logger
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - echo "===== assuming permissions => ${DEPLOYMENT_ROLE} ====="
    - KST=(`aws sts assume-role --role-arn ${DEPLOYMENT_ROLE} --role-session-name "deployment-${CI_COMMIT_TAG}" --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]' --output text`)
    - unset AWS_SECURITY_TOKEN
    - export AWS_ACCESS_KEY_ID=${KST[0]}
    - export AWS_SECRET_ACCESS_KEY=${KST[1]}
    - export AWS_SESSION_TOKEN=${KST[2]}
    - export AWS_SECURITY_TOKEN=${KST[2]}
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$LOGGER_VERSION . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$LOGGER_VERSION