name: Release 

on:
  push:
    branches:
    #- master
    - develop
    tags:
    - '*'
  pull_request:
    branches:
    #- master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build Game Runner
      run: dotnet publish --configuration Release --output ../runner-publish
      working-directory: game-runner

    - name: Build Game Engine
      run: dotnet publish --configuration Release --output ../engine-publish
      working-directory: game-engine

    - name: Build Game Logger
      run: dotnet publish --configuration Release --output ../logger-publish
      working-directory: game-logger

    - name: Assemble starter pack
      run: |
          chmod +x build_starterpack.sh
          ./build_starterpack.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: starter-pack
        path: starter-pack

  publish: 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: starter-pack
        path: starter-pack

    - name: Assemble Release
      run: zip -r starter-pack.zip starter-pack/*

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: starter-pack.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

